version: '3'

services:
  etl-worker:
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Make sure to change in .env file
      REDIS_PORT: ${REDIS_PORT}
      UPDATE_FREQ_SCHEDULES: ${UPDATE_FREQ_SCHEDULES} # Update park data every x seconds.
      UPDATE_FREQ_EXPERIENCES: ${UPDATE_FREQ_EXPERIENCES} # Update experience data every x seconds.
    depends_on:
        - redis
    restart: unless-stopped

  web:
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Make sure to change in .env file
      REDIS_PORT: ${REDIS_PORT}
      FLASK_ENV: production
    depends_on:
        - redis
        - etl-worker
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass "$REDIS_PASSWORD"
    restart: unless-stopped